# Ye.Chen
#
# Homework marco
#

#########################
# Set of the verboses
#
/control/verbose 1
/tracking/verbose 0
/run/verbose 1
/event/verbose 0


##########################
# Random
#

#/random/setDirectoryName .
#/random/setSavingFlag 1


##########################
# Initialisation procedure
#
#/geometry/textInput/verbose 3

/run/initialize

/run/beamOn 10
#/run/beamOn 10000
#/run/beamOn 100000
#100000000
